### ISSUE TITLE
json file formatting

### ISSUE THREAD

**Issue by angoodkind** [watson-developer-cloud/speech-to-text-websockets-python#14]
It seems that the json file that this outputs is actually made up of multiple json objects. This makes it very difficult to parse.

**Comment by daniel-bolanos** [comment]
Hello @angoodkind, please take a look af this line of code: 

hypothesis = jsonObject['results'][0]['alternatives'][0]['transcript']

basically that is the json object that is printed, there can be many since the service produces a stream of interim results before the final recognition results are returned (since the flag interim_results is set to true). You can customize how the JSON objects are printed, you might want to print them to different files, only print the final, etc. Or you might just use a simple regular expressions to get the individual JSON objects from the output.

**Comment by angoodkind** [comment]
Oops, sorry, I missed that line. Where does the actual printing of the json's occur in the code?
